## Make the dataframe including the emergency watter supplying for the each years and regions
- Date : Mar 21, 2023
- Author : JaeEun Yoo

In [2]:
import os
import glob
import pandas as pd
import shutil
import re

In [22]:
filename = '../샘플데이터/07. 급수현황-중부대학교, 국가가뭄정보분석센터/1994_2015.xlsx'
data = pd.read_excel(filename,header=1,sheet_name = None)
sheet_names = [k for k in data.keys()]
sheet_names

['Sheet1']

In [28]:
org_df = pd.read_excel(filename, sheet_name = sheet_names[0])
org_df = org_df[org_df.keys()[:-4]]

In [31]:
org_df = org_df.rename(columns={'피해기간\n시작일' : '피해기간_시작일', '피해기간\n종료일' : '피해기간_종료일'})

In [32]:
org_df

,시도,시군구,읍면동,피해연도,피해기간_시작일,피해기간_종료일,피해내용,피해인원,가뭄시 급수량\n(㎥/일),정상급수량\n(㎥/일),제한급수율,운반급수수단,제한급수 내용,정수용량,상수도종류
0,전라남도,완도군,신지면,1990,1990-01-01,1990-12-31,제한급수,1373.0,NaN,NaN,NaN,NaN,12시간 급수,NaN,NaN
1,경상남도,남해군,남해읍,1990,1990-01-01,1990-02-28,제한급수,9875.0,NaN,NaN,NaN,NaN,격일제,NaN,NaN
2,전라남도,완도군,군외면,1990,1990-01-01,1990-03-15,제한급수,2126.0,NaN,NaN,NaN,NaN,격일제,NaN,NaN
3,전라남도,완도군,노화읍,1990,1990-01-01,1990-12-31,제한급수,2056.0,NaN,NaN,NaN,NaN,12시간 급수,NaN,NaN
4,전라남도,완도군,금일읍,1990,1990-01-01,1990-12-31,제한급수,175.0,NaN,NaN,NaN,NaN,3시간 급수,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1417,인천광역시,강화군,내가면,2015,2015-11-20,2016-02-17,제한급수,275.0,NaN,NaN,NaN,NaN,1일 6시간 제한,80.0,마을상수도
1418,인천광역시,옹진군,자월면,2016,2016-01-01,2016-01-19,제한급수,33.0,NaN,NaN,NaN,NaN,1일 2시간 급수,100.0,소규모급수시설
1419,인천광역시,옹진군,북도면,2016,2016-03-22,2016-06-12,운반급수,330.0,NaN,NaN,NaN,선박,1회/월\n(10톤/회),NaN,마을상수도
1420,인천광역시,서구,신현원창동,2016,2016-04-06,2016-05-31,운반급수,37.0,NaN,NaN,NaN,선박,1회/월\n(1톤/회),NaN,소규모급수시설
1421,인천광역시,옹진군,덕적면,2016,2016-05-01,2016-05-24,운반급수,166.0,NaN,NaN,NaN,선박,1회/월\n(5톤/회),NaN,마을상수도

In [33]:
org_df.to_csv('../results_data/07_전국비상급수현황.csv',encoding='cp949',index=False)