## Make the dataframe including the drought indexes for the each years and regions
- Date : Mar 23, 2023
- Author : JaeEun Yoo

In [1]:
import os
import glob
import pandas as pd
import shutil
from itertools import repeat
import itertools

In [3]:
files = glob.glob('../샘플데이터/12. 기상자료개방포털_가뭄지수(SPI)/2021/*')

In [9]:
regions = ['속초','철원', '태백']

In [26]:
res = pd.DataFrame()
for i, f in enumerate(files[:3]):
    df = pd.read_csv(f,encoding='cp949')
    df['지점명'] = list(repeat(regions[i],len(df)))
    res = pd.concat([res,df])

In [27]:
c = res.keys().to_list()
cols = [c[0],c[-1]]
cols.extend(c[1:-1])

In [29]:
res = res.reindex(cols,axis=1)
res

,지점,지점명,일시,SPI1,SPI2,SPI3,SPI4,SPI5,SPI6,SPI9,SPI12,SPI18,SPI24
0,90,속초,2021-01-01,-1.59,-1.68,-2.52,0.59,1.08,1.45,2.18,2.41,2.14,1.80
1,90,속초,2021-01-02,-1.44,-1.62,-2.52,0.72,1.11,1.46,2.20,2.42,2.17,1.81
2,90,속초,2021-01-03,-1.34,-1.52,-2.49,-0.02,1.13,1.51,2.20,2.43,2.20,1.81
3,90,속초,2021-01-04,-1.34,-1.51,-2.49,-0.38,1.14,1.54,2.19,2.44,2.22,1.81
4,90,속초,2021-01-05,-1.33,-1.49,-2.51,-0.37,0.75,1.64,2.20,2.44,2.27,1.81
...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,216,태백,2021-12-27,-0.32,-0.92,-0.28,-0.29,-0.01,-0.44,-0.06,-0.26,0.74,0.37
361,216,태백,2021-12-28,-0.26,-0.93,-0.20,-0.26,0.00,-0.41,-0.15,-0.26,0.75,0.37
362,216,태백,2021-12-29,-0.20,-0.91,-0.19,-0.21,0.02,-0.40,-0.15,-0.26,0.75,0.37
363,216,태백,2021-12-30,-0.17,-0.91,-0.31,-0.33,0.06,-0.37,-0.15,-0.26,0.73,0.37
364,216,태백,2021-12-31,-1.60,-0.95,-0.28,-0.28,0.07,-0.42,-0.14,-0.26,0.62,0.37

In [30]:
res.to_csv('../results_data/12_가뭄지수_2021.csv',encoding='cp949',index=False)

In [19]:
len(df.keys())

13