## Make the dataframe including the evapotranspiration for the each years and regions
- Date : Mar 20, 2023
- Author : JaeEun Yoo

In [1]:
import os
import glob
import pandas as pd
import shutil
import re

In [2]:
root_path = '../샘플데이터/13. 한국수문조사연보(유량편)_증발산량/'
year_list = glob.glob(root_path+'/*')
year_list.sort()

In [3]:
year_list

['../샘플데이터/13. 한국수문조사연보(유량편)_증발산량/2010',
 '../샘플데이터/13. 한국수문조사연보(유량편)_증발산량/2011',
 '../샘플데이터/13. 한국수문조사연보(유량편)_증발산량/2012',
 '../샘플데이터/13. 한국수문조사연보(유량편)_증발산량/2013',
 '../샘플데이터/13. 한국수문조사연보(유량편)_증발산량/2014',
 '../샘플데이터/13. 한국수문조사연보(유량편)_증발산량/2015',
 '../샘플데이터/13. 한국수문조사연보(유량편)_증발산량/2016',
 '../샘플데이터/13. 한국수문조사연보(유량편)_증발산량/2017',
 '../샘플데이터/13. 한국수문조사연보(유량편)_증발산량/2018',
 '../샘플데이터/13. 한국수문조사연보(유량편)_증발산량/2019',
 '../샘플데이터/13. 한국수문조사연보(유량편)_증발산량/2020',
 '../샘플데이터/13. 한국수문조사연보(유량편)_증발산량/2021']

# 2015

In [4]:
files = glob.glob(year_list[5]+'/*.xls')

In [5]:
files.sort()
files

['../샘플데이터/13. 한국수문조사연보(유량편)_증발산량/2015/일증발산량 연표(2015).xls',
 '../샘플데이터/13. 한국수문조사연보(유량편)_증발산량/2015/증발산량관측소 일람표(2015).xls']

In [6]:
data = pd.read_excel(files[0],header=3,sheet_name=None)
sheet_names = [k for k in data.keys()]

In [7]:
sheet_names

['청미천2015', '설마천2015', '덕유산2015', '무안2015']

In [8]:
data = pd.read_excel(files[0],header=3,sheet_name = sheet_names[0])
data = data.drop([0])
data = data.reset_index(drop=True)
data = data[:31]

In [31]:
year = '2015'
columns_list = ['Region','Address', 'Year','Month','Day','Evapotrans(mm/d)','GapFilled']

In [33]:
res = pd.DataFrame(columns=columns_list)
for region in sheet_names:
    data = pd.read_excel(files[0],header=1,sheet_name = region)
    addr = data['Unnamed: 12'][0].split(',')[0].split(':')[1][1:]
    print(addr)
    
    data = pd.read_excel(files[0],header=3, sheet_name = region)
    data = data.drop([0])
    data = data.reset_index(drop=True)
    data = data[:31]
    region = re.sub(r'[0-9]','', region)

    for m in data.columns[1:13]:
        for d in data[data.columns[0]]:
            if str(data[m].iloc[d-1])[-1] == '*':
                items = pd.DataFrame({'Region':region,
                                      'Address': addr,
                                     'Year':year, 
                                     'Month' :m, 
                                     'Day' : str(d),
                                     'Evapotrans(mm/d)' : str(data[m][d-1])[:-1],
                                     'GapFilled' : '1'}, index=[0])
            else:
                if str(data[m].iloc[d-1]) == ' ':
                    break
                else:
                    items = pd.DataFrame({'Region':region,
                                          'Address':addr,
                             'Year':year, 
                             'Month' :m, 
                             'Day' : str(d),
                            'Evapotrans(mm/d)':data[m][d-1],
                             'GapFilled' : '0'}, index=[0])
            res = pd.concat([res,items],ignore_index=True)
            
    res = res.dropna(axis=0)
res.to_csv('../results_data/13_일증발산량_'+year+'.csv',index=False,encoding='cp949')

경기도 여주군 점동면 뇌곡리
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
경기도 파주시 적성면 설마리 감악산
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
전라북도 무주군 안성면 덕산리 산 6번지
전라남도 무안군 일로읍 복룡리 2527
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap
Gap

In [34]:
res

     Region                Address  Year Month Day Evapotrans(mm/d) GapFilled
0       청미천        경기도 여주군 점동면 뇌곡리  2015    1월   1              0.4         0
1       청미천        경기도 여주군 점동면 뇌곡리  2015    1월   2              0.3         0
2       청미천        경기도 여주군 점동면 뇌곡리  2015    1월   3              0.2         0
3       청미천        경기도 여주군 점동면 뇌곡리  2015    1월   4              0.2         0
4       청미천        경기도 여주군 점동면 뇌곡리  2015    1월   5              0.1         0
...     ...                    ...   ...   ...  ..              ...       ...
1398     무안  전라남도 무안군 일로읍 복룡리 2527  2015   12월  27              0.3         0
1399     무안  전라남도 무안군 일로읍 복룡리 2527  2015   12월  28              0.2         0
1400     무안  전라남도 무안군 일로읍 복룡리 2527  2015   12월  29              0.3         1
1401     무안  전라남도 무안군 일로읍 복룡리 2527  2015   12월  30              0.2         0
1402     무안  전라남도 무안군 일로읍 복룡리 2527  2015   12월  31              0.2         1

[1403 rows x 7 columns]